version: "3.9"

services:
  api:
    image: myapp/api:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DefaultConnection}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Cors__Origins=${Cors__Origins}
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - ./data:/app/data
    networks:
      - app-network

  web:
    image: myapp/web:latest
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
