services:
  api:
    image: myapp/api:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__DefaultConnection
      - Jwt__SecretKey
      - Jwt__Issuer
      - Jwt__Audience
      - Cors__PolicyName
      - Cors__Origins
      - ASPNETCORE_URLS
      - DOTNET_RUNNING_IN_CONTAINER
    volumes:
      - ./data:/app/data
    networks:
      - app-network

  web:
    image: myapp/web:latest
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
