services:
  db:
    image: postgres:16
    container_name: app_db_1
    restart: always
    environment:
      POSTGRES_USER: alyson
      POSTGRES_PASSWORD: alyson123
      POSTGRES_DB: bancopostgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alyson"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./src/API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Cors__PolicyName=${Cors__PolicyName}
      - Cors__Origins=${Cors__Origins}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - DOTNET_RUNNING_IN_CONTAINER=${DOTNET_RUNNING_IN_CONTAINER}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.env.yml
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
