services:
  db:
    image: postgres:16
    container_name: app_db_1
    restart: always
    environment:
      POSTGRES_USER: alyson
      POSTGRES_PASSWORD: alyson123
      POSTGRES_DB: bancopostgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: myapp/api:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Cors__PolicyName=${Cors__PolicyName}
      - Cors__Origins=${Cors__Origins}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - DOTNET_RUNNING_IN_CONTAINER=${DOTNET_RUNNING_IN_CONTAINER}
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: myapp/web:latest
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
