name: CI/CD Deploy otimizado

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build da imagem Docker API
      run: docker build -t myapp/api:latest -f src/API/Dockerfile .

    - name: Build da imagem Docker Web
      run: docker build -t myapp/web:latest -f web/Dockerfile .

    - name: Exportar imagens como image-api.tar.gz e image-web.tar.gz
      run: |
        docker save myapp/api:latest | gzip > ./image-api.tar.gz
        docker save myapp/web:latest | gzip > ./image-web.tar.gz

    - name: Criar arquivo .env com variáveis do secrets
      run: |
        echo "ASPNETCORE_ENVIRONMENT=Production" > .env
        echo "ConnectionStrings__DefaultConnection=${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}" >> .env
        echo "Jwt__SecretKey=${{ secrets.JWT__SECRETKEY }}" >> .env
        echo "Jwt__Issuer=${{ secrets.JWT__ISSUER }}" >> .env
        echo "Jwt__Audience=${{ secrets.JWT__AUDIENCE }}" >> .env
        echo "Cors__PolicyName=${{ secrets.CORS__POLICYNAME }}" >> .env
        echo "Cors__Origins=${{ secrets.CORS__ORIGINS }}" >> .env
        echo "ASPNETCORE_URLS=http://+:5000" >> .env
        echo "DOTNET_RUNNING_IN_CONTAINER=true" >> .env

    - name: Listar arquivos na pasta atual (debug)
      run: |
        ls -lh ./image-*.tar.gz compose.yml .env

    - name: Enviar imagens, compose.yml e .env para a VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "image-api.tar.gz,image-web.tar.gz,compose.yml,.env"
        target: "/home/${{ secrets.VM_USER }}/app"

    - name: Rodar docker-compose na VM com imagens carregadas e carregar .env
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        timeout: 60m
        command_timeout: 60m
        script: |
          cd /home/${{ secrets.VM_USER }}/app
          docker-compose -f compose.yml down --remove-orphans
          docker image rm myapp/api:latest || true
          docker image rm myapp/web:latest || true
          gunzip -c image-api.tar.gz | docker load
          gunzip -c image-web.tar.gz | docker load
          docker-compose --env-file .env -f compose.yml up -d
